services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ArticleHub\BehatExtension\EventListener\TokenListener:
        arguments:
            $kernel: '@symfony2_extension.kernel'
        tags:
            - { name: 'event_dispatcher.subscriber' }
