api_user:
    user_class: ArticleHub\Entity\User
    login_credential: email
    from_email:
        address: !php/const ArticleHub\Enum\EmailAddress::ARTICLE_HUB_EMAIL
        sender_name: !php/const ArticleHub\Enum\EmailAddress::ARTICLE_HUB_NAME
