lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASS_PHRASE)%'
    token_ttl: '%env(resolve:JWT_TOKEN_TTL)%'
    user_identity_field: email
