version: '3.4'

services:
  article-hub-api:
    image: ${CONTAINER_REGISTRY_BASE}
    build:
      context: ./
      target: article_hub
    depends_on:
      - db
    external_links:
      - rabbitmq
    env_file:
      - ./.env.local
    volumes:
      - ./:/srv/api:rw,cached
    ports:
      - "8080:80"
    networks:
      - api-net

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=article_hub
      - MYSQL_USER=article_hub
      - MYSQL_PASSWORD=myadmin
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - api-net

networks:
  api-net:
    external:
      name: api-net

volumes:
  db-data: {}
