monolog:
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: debug
            channels: ["!deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            level: warning
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
